version: '3.1'

services:
  image: mysql:5.7
    container_name: mysql-5.7
    volumes:
      - ~/docker/mysql/data:/var/lib/mysql
      - ~/docker/mysql/config:/etc/mysql/conf.d
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "hello"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_ROOT_PASSWORD: "root"

mongodb:
  mysql:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ~/docker/mongo/data/db:/data/db
    container_name: "mongodb"
    ports:
      - "27017:27017"
